<template>
  <v-menu
  offset-y open-on-hover transition="scale-transition" max-width="300px">
    <template v-slot:activator="{ on, attrs }">
      <span 
      @click.stop
      small
      v-bind="attrs"
      v-on="on"
      color="textFaint"
      class="white--text primary-pulse primary px-2 br-20 caption font-weight-bold">
        <v-icon color="white" small>mdi-leaf</v-icon>
        ENMT
      </span>
    </template>
    <div class="pa-3 foreground caption">
      <div class="text-center">
        <v-icon color="white" size="30" class="primary br-c pa-2">mdi-leaf</v-icon>
      </div>
      <div class="text-center py-3 primary--text font-weight-bold">
        This ENMT token was generated by the Unicrypt Token factory.
      </div>
      <div class="d-flex align-start">
        <v-icon size="20" color="primary" class="mr-1">mdi-check-circle</v-icon>
        No mint function
      </div>
      <div class="d-flex align-start">
        <v-icon size="20" color="primary" class="mr-1">mdi-check-circle</v-icon>
        No owner / admin functions
      </div>
      <div class="d-flex align-start">
        <v-icon size="20" color="primary" class="mr-1">mdi-check-circle</v-icon>
        No unsafe code in the token contract itself
      </div>
      <div class="d-flex align-start">
        <v-icon size="20" color="primary" class="mr-1">mdi-check-circle</v-icon>
        Fully ERC20 compliant
      </div>
      <div class="d-flex align-start">
        <v-icon size="20" color="primary" class="mr-1">mdi-check-circle</v-icon>
        Fully decentralised
      </div>
      <!-- MINT YOUR OWN -->
      <v-btn color="primary" block rounded to="/services/minter" class="mt-2">
        Mint your own ENMT
      </v-btn>
    </div>
  </v-menu>
</template>